// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYSQDdUJM7Qv8OpuAxRgMMfVRaDZUXxyk',
    appId: '1:654195767460:web:61329e159895496b654e31',
    messagingSenderId: '654195767460',
    projectId: 'classpal-633f7',
    authDomain: 'classpal-633f7.firebaseapp.com',
    databaseURL: 'https://classpal-633f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'classpal-633f7.firebasestorage.app',
    measurementId: 'G-CFPGV08CLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMNv0tGJ1ku-sA1B9UjTbLGPshjpvkV_Q',
    appId: '1:654195767460:android:bbb8e69a1c3dab06654e31',
    messagingSenderId: '654195767460',
    projectId: 'classpal-633f7',
    databaseURL: 'https://classpal-633f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'classpal-633f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMp4Mvqk4tg-PFXA84ucLWFl4CI68ZmkM',
    appId: '1:654195767460:ios:0c64c8749fa57258654e31',
    messagingSenderId: '654195767460',
    projectId: 'classpal-633f7',
    databaseURL: 'https://classpal-633f7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'classpal-633f7.firebasestorage.app',
    iosBundleId: 'com.example.mobileClasspal',
  );
}
